### PR TITLE
Add restartable wrapper generator

### PR DESCRIPTION
**Pull request by olivierdagenais**
Using some mad CodeDOM skillz and some reflection, the `RestartableAddInGenerator` can be pointed at Host View interfaces to automatically generate `Restartable` wrappers.  All it needs is a tool interface to do so; maybe an MSBuild task that accepts an `ITaskItem` representing an assembly to scan, another `ITaskItem` representing the output folder and a `String` representing the target namespace?  Suggestions welcome.

### CODE REVIEW

**Comment by olivierdagenais** [comment]
While waiting for this pull request yesterday, I decided to go ahead and finish the public interface of `RestartableAddInGenerator`, which is mostly in 94098f7aba93b9cc04168bc7feb0d45754cbb467.

**Comment by JefStat** [comment]
I'm not clear on how MSBuild could scan an assembly and find the correct interface then pipe that to this assembly. I'm just missing the knowledge about these capabilities in msbuild. 

From what I know and seen. I like to include the generated file into the .csproj using a prebuild event to kick off the generator such that the file exist when the compiling is started. I don't know what the task would like like and how you would write it but I know I definitely prefer this to the dynamic compiling that CodeDom allows witch would be a big security risk.

**Comment by olivierdagenais** [comment]
> I'm not clear on how MSBuild could scan an assembly and find the correct interface then pipe that to this assembly.

As discussed, I see two ways of doing this:
1. We generate the source code for a new assembly, which is compiled after the HostViews have been compiled and the `RestartableAddInGenerator` has scanned the latter.
2. We still scan the HostViews assembly after it was compiled, but then we do something like Microsoft's Orleans grain projects do and merge the generated code into the HostViews assembly. This is described in [Generating the Class Factory](https://dotnet.github.io/orleans/Getting-Started-With-Orleans/Developing-a-Grain#generating-the-class-factory):

> After the grain interface has been defined, building the project originally created with the Orleans Visual Studio project template will use the Orleans-specific MSBuild targets to generate client proxy and factory classes corresponding to the user-defined grain interfaces, and to merge this additional code back into the interface DLL.

**Comment by olivierdagenais** [comment]
> I'm wondering if you would want to strip the whitespace from the string and output before the assertion so you don't have to worry about the formatting of the compiled code.

Is it OK if I contribute such a method to a `Solink.Testing` project, then use it here later?

**Comment by JefStat** [comment]
> Is it OK if I contribute such a method to a Solink.Testing project, then use it here later?

Not a problem.

**Pull request merged**
